import { TableRowData } from "@/app/dashboard/_documents/_components/dataTable";

export const sampleTableData: TableRowData[] = [
  {
    id: "1",
    fileName: "forward statement item 2.txt",
    status: "Archived",
    fileType: "DOC",
    category: "Technical doc",
    tags: [
      { label: "Materials", color: "blue" },
      { label: "Construction", color: "indigo" },
      { label: "Site", color: "blue" },
      { label: "Photo", color: "indigo" },
      { label: "Technical", color: "gray" },
      { label: "Planning", color: "blue" },
    ],
    size: "245 KB",
    uploaded: "15/05/2020",
    parsingStatus: "completed",
  },
  {
    id: "2",
    fileName: "Sheet 1.xls",
    status: "Draft",
    fileType: "XLS",
    category: "Financial doc",
    tags: [
      { label: "Photo", color: "blue" },
      { label: "Materials", color: "indigo" },
    ],
    size: "1.2 MB",
    uploaded: "09/05/2019",
    parsingStatus: "processing",
  },
  {
    id: "3",
    fileName: "legal-tenure.pdf",
    status: "Accepting Bids",
    fileType: "PDF",
    category: "Technical doc",
    tags: [
      { label: "Site", color: "blue" },
      { label: "Construction", color: "indigo" },
      { label: "Legal", color: "gray" },
      { label: "Documentation", color: "blue" },
      { label: "Review", color: "indigo" },
    ],
    size: "856 KB",
    uploaded: "15/05/2020",
    parsingStatus: "completed",
  },
  {
    id: "4",
    fileName: "DF_ASKD_UED_changed_2393_very_long_filename_example.pdf",
    status: "Deadline Passed",
    fileType: "PDF",
    category: "Financial doc",
    tags: [
      { label: "Materials", color: "blue" },
      { label: "Photo", color: "indigo" },
    ],
    size: "2.1 MB",
    uploaded: "09/05/2019",
    parsingStatus: "processing",
  },
  {
    id: "5",
    fileName: "doument_1.pdf",
    status: "Awarded",
    fileType: "PDF",
    category: "Media doc",
    tags: [
      { label: "Construction", color: "blue" },
      { label: "Costs", color: "indigo" },
    ],
    size: "512 KB",
    uploaded: "20/03/2020",
    parsingStatus: "failed",
  },
  {
    id: "6",
    fileName: "FunnyMemeOMG.gif",
    status: "Archived",
    fileType: "PPTX",
    category: "Technical doc",
    tags: [
      { label: "Site", color: "blue" },
      { label: "Materials", color: "indigo" },
    ],
    size: "3.4 MB",
    uploaded: "15/05/2020",
    parsingStatus: "completed",
  },
  {
    id: "7",
    fileName: "Scann_158.pdf",
    status: "Deadline Passed",
    fileType: "PDF",
    category: "Media doc",
    tags: [
      { label: "Photo", color: "blue" },
      { label: "Site", color: "indigo" },
    ],
    size: "1.8 MB",
    uploaded: "15/05/2020",
    parsingStatus: "failed",
  },
  {
    id: "8",
    fileName: "ATTACHEMENT_836128956_very_long_document_name.html",
    status: "Accepting Bids",
    fileType: "PDF",
    category: "Financial doc",
    tags: [
      { label: "Materials", color: "blue" },
      { label: "Construction", color: "indigo" },
    ],
    size: "4.2 MB",
    uploaded: "15/05/2020",
    parsingStatus: "completed",
  },
];
